---
apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: kube-system
spec:
  ports:
    - port: 3307
      targetPort: 3306
      name: http
      #nodePort: 32000
  selector:
    app: database-pod
  sessionAffinity: ClientIP
  #type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-pod
  template:
    metadata:
      name: database-pod
      namespace: kube-system
      labels:
        app: database-pod
    spec:
      containers:
        - image: mysql
          name: dev-container
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: db-secret

          #env:
            #- name: MYSQL_ROOT_PASSWORD
              #value: "abcde"
            #- name: MYSQL_DATABASE
              #value: "dbspring"
            #- name: MYSQL_USER
              #value: "keycloak"
           # - name: MYSQL_PASSWORD
              #value: "keycloak"

          ports:
            - containerPort: 3306
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
      volumes:
       - name: mysql-data
         emptyDir: {}
  #kubectl port-forward service/dev-java-service 7080:8087
